name: CD

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/setup-node@v4

          - name: Set up Node
            uses: actions/setup-node@v4
            with:
              node-version: 20

          - name: Install Dependencies
            run: npm ci

          - name: Build
            run: npm run build