name: CD

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        #github action secrets
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Node
            uses: actions/setup-node@v4
            with:
              node-version: 20

          - name: Install Dependencies
            run: npm ci

          - name: Build
            run: npm run build

          - name: Authenticat to Google Cloud
            id: auth
            uses: google-github-actions/auth@v2
            with:
              credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      
            #Setup gcloud CLI with v3
          - name: Set up Cloud SDK
            uses: google-github-actions/setup-gcloud@v3
      

            #Configure Docker to use gcloud credentials
          - name: Configeure Docker authentication
            run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

            #Build and push docker image to Artifact Registry
          - name: Build and Push Docker image
            run: | 
              IMAGE="us-central1-docker.pkg.dev/notely-474220/notely-ar-repo/notely:latest"
              gcloud builds submit --tag "$IMAGE" .
          
          - name: Database Migration
            run: npm run db:migrate
            
          - name: Deploy to Cloud Run
            run: gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-474220/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-474220 --max-instances=4

