
name: ci

on:
  pull_request:
    branches: [main]

  push:
    branches: ["*"]


jobs:
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with: 
          node-version: 20

      - name: Install dependencies
        run: npm ci
        
      - name: Format code
        run: npm run format:check

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4  #pulls the repo into vm

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        
      - name: run tests
        run: npm run test -- --coverage